services:
  frontend:
    container_name: suml-frontend
    image: pjatksuml/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - drone-network

  backend:
    container_name: suml-backend
    image: pjatksuml/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge