name: Build and deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure using AZURE_CREDENTIALS
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Docker login to ACR
      run: |
        az acr login --name birddrone

    - name: Build and push image
      run: |
        docker build -t birddrone.azurecr.io/pjatksuml/frontend:latest ./frontend
        docker push birddrone.azurecr.io/pjatksuml/frontend:latest

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v2
      with:
        resourceGroup: suml
        containerAppName: bird-drone-frontend
        imageToDeploy: birddrone.azurecr.io/pjatksuml/frontend:latest
