name: Build, Push and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: birddrone.azurecr.io/pjatksuml/frontend:latest

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: birddrone.azurecr.io/pjatksuml/backend:latest

    - name: Deploy frontend to Azure Container Apps
      uses: azure/azure-container-apps-deploy@v1
      with:
        app-name: bird-drone-frontend
        resource-group: suml
        image: birddrone.azurecr.io/pjatksuml/frontend:latest
        registry-server: birddrone.azurecr.io
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}

    - name: Deploy backend to Azure Container Apps
      uses: azure/azure-container-apps-deploy@v1
      with:
        app-name: bird-drone-backend
        resource-group: suml
        image: birddrone.azurecr.io/pjatksuml/backend:latest
        registry-server: birddrone.azurecr.io
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
