# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker Images using Compose
        run: docker compose -f docker-compose.yml build

      - name: Run Trivy vulnerability scanner for frontend
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'pjatksuml/frontend'
          format: 'sarif'
          output: 'trivy-results-frontend.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          timeout: 20m
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Run Trivy vulnerability scanner for backend
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'pjatksuml/backend'
          format: 'sarif'
          output: 'trivy-results-backend.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          timeout: 20m
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload Trivy scan results for frontend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-frontend.sarif'

      - name: Upload Trivy scan results for backend
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-backend.sarif'